services:
  db:
    image: postgres:15.5-bookworm
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
